### ISSUE TITLE
Move failing Miner to 'Failed' (Enhancement)

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#11]
It's unclear at the moment to see which miners failed. After restarting, failed miners may retry benchmark. This results both in lost time and uncertainity.

Why not moving miners -when failed multiple times- to a subfolder called 'Failed'? Then it's still up to me to decide if I want to retry them (cfr. put them back in the 'Miners' folder), maybe with different settings?

As a complication to this: miner files contain multiple algo's, some of them may fail while others work fine. This potentially could be solved by moving only the failed algo's to the 'Failed' sub folder... however this may complicate things too much for now.

To workaround that, you could start with single-algo miners (cfr. when they fail, move them to the 'Failed' folder).

**Comment by yuzi-co** [comment]
The benchmarking should be automatic, but some human intervention may be required

If a miners fails it can be caused by specific hardware/miner/network/pool or even other programs running, therefore it's better to investigate the reason why instead of silently removing it.
I'd rather not have MM play with miner files and leave that to a human.

It is possible that some settings are tweaked too high for some hardware or even not defined correctly

If something fails, you can move the miner yourself or add it in "ExcludeMiners_XXX" config (where XXX is the device group).

**Comment by eMTee72** [comment]
How to (easily) find out which miners failed?

Yes, one could manually check all miners manually, comparing them with 'Best Miners /All' and 'Top 10/All'. But that tkaes a lot of time and effort.
And I guess one could also check the log files to get some hints. But again, that takes a lot of time and effort.

So maybe I'm missing something, but at the moment I do not know of a way to check which miners/algo's failed (either while benchmarking or later on).

**Comment by yuzi-co** [comment]
currently, the easiest, would be to rerun MM after all was benchmarked and see the miners that are shown as "benchmarking"
perhaps I'll add a more obvious entry in the log file so you can easily search for it
most of the logs are still tutulino's work and I haven't change them much

**Comment by eMTee72** [comment]
Rerunning MM is what I was referring to as 'takes a lot of time and effort'. Even marking them in the log, although already helpfull for troubleshooting, doesn't prevent MM to retry benchmarking them at the next run.
I guess I'm trying to achieve too many things at once here: identyfying the failed algo/miners AND fixing it for future runs.

**Comment by eMTee72** [comment]
Didn't see you previous comment. Fair enough, I can live with it (for now)   :-)
