### ISSUE TITLE
3 issues in 1 Log file?

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#15]
Also see attached Log-file... 
[2018-04-30_21-31-43.txt](https://github.com/yuzi-co/Megaminer/files/1961932/2018-04-30_21-31-43.txt)

Issue 1: ###### ERROR ##### Could not find a part of the path

Issue 2: ClayDual 11.7 detects my GPU's as 'GeForce GTX 1060 3GB', then mentions 'All GPUs are 2GB, miner is completely free in this case, developer fee will not be mined at all', followed by 'too high epoch number for 3GB card in Windows 10' and halts. This may not be related to MM though... just think it's strange that it's sometimes reported as a 2GB version... Probably need to reach out to Claymore for this?

Issue 3: MM then considers all my miners as not OK due to: 'skipped due to constraints'), then exits with message: 'Miners/Pools combinations detected: 0' & 'NO MINERS!'

**Comment by yuzi-co** [comment]
1. I need investigate. nothing critical

2. not an error. Claymore didn't change the wording when enabling "no fee" on 3GB cards.
3GB cards probably do not work already with ETH due to DAG size. newer Ethash coins still work

3. fixed in 7efadcb98d8ea7d4e9a90387cd81145efcf79bd2

Apologies for the inconvenience

**Comment by toshkov02** [comment]
You're cool. You quickly corrected the mistake. Thank you.
